server:
  port: 8080
spring:
  application:
    name: api-gateway
cloud:
  gateway:
    routes:
      - id: home-service
        uri: lb://HOME-SERVICE
        predicates:
          -path=/home/**
discovery:
  locator:
    enabled: true          
    
